# -*- coding: utf-8 -*-
"""
Indices for the state variables
"""

# Returns idx, a dictionary containing the state variable names ('keys') and their corresponding index ('values')
def set_indices():
    
    idx = { 'R': 0,         # Arteriolar radius [um]
            'E_t': 1,       # Proportion of excitatory cells firing per unit time [-]        
            'I_t': 2,       # Proportion of inhibitory cells firing per unit time [-]      
            'K_e': 3,       # Extracellular K+ concentration [mM]       
            'Na_sa': 4,     # Na+ concentration in the soma/axon [mM]       
            'Na_d': 5,      # Na+ concentration in the dendrite [mM]    
            'O2': 6,        # Tissue oxygen concentration [mM]        
            'CBV': 7,       # Nondimensional cerebral blood volume [-]    
            'HbR': 8,       # Normalised deoxyhemoglobin concentration [-]       
            'Ca_n': 9,      # Neuronal Ca2+ concentration [uM]       
            'nNOS': 10,     # Neuronal nitric oxide synthase concentration [uM]
            'NO_n': 11,     # Neuronal nitric oxide concentration [uM]         
            'v_k': 12,      # Astrocytic membrane potential [mV] 
            'K_p': 13,      # Perivascular K+ concentration [uM] 
            'Ca_p': 14,     # Perivascular Ca2+ concentration [uM] 
            'Na_k': 15,     # Astrocytic Na+ concentration [uM]
            'K_k': 16,      # Astrocytic K+ concentration [uM] 
            'Cl_k': 17,     # Astrocytic Cl- concentration [uM] 
            'HCO3_k': 18,   # Astrocytic HCO3- concentration [uM]
            'Na_s': 19,     # Synaptic Na+ concentration [uM] 
            'K_s': 20,      # Synaptic K+ concentration [uM] 
            'HCO3_s': 21,   # Synaptic HCO3- concentration [uM] 
            'w_k': 22,      # Open probability of the astrocytic BK channel [-] 
            'I_k': 23,      # Astrocytic IP3 concentration [uM]
            'Ca_k': 24,     # Astrocytic Ca2+ concentration [uM] 
            'h_k': 25,      # Inactivation variable of the astrocytic IP3R channel [-] 
            's_k': 26,      # Ca2+ concentration in the astrocytic ER [uM] 
            'm_k': 27,      # Open probability of the astrocytic TRPV4 channel [-] 
            'eet_k': 28,    # Astrocytic EET concentration [uM] 
            'NO_k': 29,     # Astrocytic nitric oxide concentration [uM] 
            'AA_k': 30,     # Astrocytic arachidonic acid concentration [uM]
            'Ca_i': 31,     # SMC Ca2+ concentration [uM]
            's_i': 32,      # Ca2+ concentration in the SR of the SMC [uM]
            'v_i': 33,      # SMC membrane potential [mV]
            'w_i': 34,      # Open probability of the SMC BK channel [-]
            'I_i': 35,      # SMC IP3 concentration [uM]
            'NO_i': 36,     # SMC nitric oxide concentration [uM] 
            'E_b': 37,      # Fraction of sGC in the basal state [-]
            'E_6c': 38,     # Fraction of sGC in the intermediate form [-] 
            'cGMP_i': 39,   # SMC cGMP concentration [uM]
            'H_i': 40,      # SMC 20-HETE concentration [uM]
            'AA_i': 41,     # SMC arachidonic acid concentration [uM]
            'Ca_j': 42,     # EC Ca2+ concentration [uM]
            's_j': 43,      # Ca2+ concentration in the ER of the EC [uM]
            'v_j': 44,      # EC membrane potential [mV]
            'I_j': 45,      # EC IP3 concentration [uM]
            'eNOS': 46,     # Endothelial nitric oxide synthase concentration [uM]
            'NO_j': 47,     # EC nitric oxide concentration [uM] 
            'Mp': 48,       # Fraction of free phosphorylated cross-bridges [-]
            'AMp': 49,      # Fraction of attached phosphorylated cross-bridges [-]
            'AM': 50,       # Fraction of attached dephosphorylated cross-bridges [-]
            'GABA': 51,     # Normalised GABA concentration [-]
            'Glu': 52,      # Normalised glutamate concentration [-]
            'NPY': 53}      # Normalised NPY concentration [-]

    return idx